### ISSUE TITLE
Postman

### ISSUE THREAD

**Issue by ghost** [enspiral-root-systems/catstack#61]
When I use Postman to create new todo via POST : `http://localhost:5000/api/todos?complete=false&text=Something` the response is : 

`{
  "id": 7,
  "text": null,
  "complete": null
}`

**Comment by ghost** [comment]
Forgot the content-type:json prop

**Comment by ahdinosaur** [comment]
hey @naptiv, similar to #60, would you mind adding something to the [FAQ](https://github.com/enspiral-craftworks/business-stack#faq) for this?
